// ---------------------------------------------------------------------------
// Stacking data — auto-generated by simulations/fetch-stacking-data.ts
// ---------------------------------------------------------------------------

/**
 * MIA stacking data for cycles 82 and 83, fetched from mainnet.
 *
 * Each entry represents a user's stacking amounts:
 *   Cycle 82: at STX block 145,643 (BTC 838,250)
 *   Cycle 83: at STX block 147,282 (BTC 840,350)
 *
 * Source: ccd007-citycoin-stacking.get-stacker(u1, cycle, userId)
 * Principal: ccd003-user-registry.get-user(userId)
 */
export const stackingData: {
  address: string;
  cycle82Stacked: bigint;
  cycle83Stacked: bigint;
}[] = [
  {
    address: "SP0ESHJJ1FA7KBJ26SE4Z5W4TQR2BWPDX8PX72GK",
    cycle82Stacked: 286026000000n,
    cycle83Stacked: 286026000000n,
  },
  {
    address: "SP12WX5WJSKYETBGE7E3NMDQTW17K99T4C5ZEJC6F",
    cycle82Stacked: 299976000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP13EZ58DXARG85WFX41KKSPZ9G8BTADRZCTZEZMM",
    cycle82Stacked: 3798495000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP13NKC4KRXT3QVE1AWYNM10SRGPJ59J9TWA8HAQS",
    cycle82Stacked: 108612000000n,
    cycle83Stacked: 108612000000n,
  },
  {
    address: "SP143YHR805B8S834BWJTMZVFR1WP5FFC03WZE4BF",
    cycle82Stacked: 5386156000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP14WPH8AMBFF0X45EJTE3T00P7GTD5GX43SDTGXD",
    cycle82Stacked: 52967000000n,
    cycle83Stacked: 52967000000n,
  },
  {
    address: "SP18R44071H3AJD1Z1HR4GAAS2FE0PQ33ADMWKSJP",
    cycle82Stacked: 50000000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP18WRH4SF7F1M5QZZ2BQDZZYBCJWT9VWQMDSTFY5",
    cycle82Stacked: 16652000000n,
    cycle83Stacked: 16652000000n,
  },
  {
    address: "SP19264KS3Z0BN93RHZKM0DKP9D1WPQ27FWKPMM3C",
    cycle82Stacked: 96042000000n,
    cycle83Stacked: 96042000000n,
  },
  {
    address: "SP1934QK1ZXGCEBB3MN9Y0FNR20GMDWM3Y5P5VV5",
    cycle82Stacked: 1337281000000n,
    cycle83Stacked: 1337281000000n,
  },
  {
    address: "SP19WSDJWTH4CW3YG554XS5CAXJJGAN83P8CFZ4K1",
    cycle82Stacked: 1142330000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP1AQDVJF18XEFVXMWTRAW9TQ0N2DCN0178FKW03R",
    cycle82Stacked: 2263000000n,
    cycle83Stacked: 2263000000n,
  },
  {
    address: "SP1BCE6B3Q5ET0H9HNV7SZJQR3MSGB8QWGG5AXCAQ",
    cycle82Stacked: 0n,
    cycle83Stacked: 71145000000n,
  },
  {
    address: "SP1C6WQ9KTV3769S8X8YNAWBXKDG2Y65P5EEDRWR6",
    cycle82Stacked: 2298988000000n,
    cycle83Stacked: 2298988000000n,
  },
  {
    address: "SP1E5KVXXSSBT5D3ZRBPCT33PNR9EDEN5341XGQ70",
    cycle82Stacked: 11720000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP1J4W7VYR4QXZKSPSMV70EFCD5DH50GKKE6T8VCK",
    cycle82Stacked: 251019000000n,
    cycle83Stacked: 251019000000n,
  },
  {
    address: "SP1NNJSHTNQ551JNJB79YVNY16EW9AW50YF60AREW",
    cycle82Stacked: 0n,
    cycle83Stacked: 2000000000n,
  },
  {
    address: "SP1PKK6KJPM826D0X6AMCJ63KEH2M456M4T22WAPQ",
    cycle82Stacked: 323000000n,
    cycle83Stacked: 323000000n,
  },
  {
    address: "SP1Q849DX9ER6STVMCWEXACXZF8S21YMSYBTGGDJP",
    cycle82Stacked: 16763000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP1QF902WKKJ0YHT6BD5Q5GSWHM7RKR53MWWN8PHR",
    cycle82Stacked: 68393000000n,
    cycle83Stacked: 68393000000n,
  },
  {
    address: "SP1SSF31YH31HQ5VPJ7ZRB17ZT5TBPG79YQZPXKW8",
    cycle82Stacked: 12750000000n,
    cycle83Stacked: 12750000000n,
  },
  {
    address: "SP1SYW6GETS33ZDY40N502NK8014KM4BTQ4RE4FS1",
    cycle82Stacked: 392962000000n,
    cycle83Stacked: 392962000000n,
  },
  {
    address: "SP1SZ9W813P723B8H27TZGTG7MZPKQB7JT149HH4Q",
    cycle82Stacked: 0n,
    cycle83Stacked: 318345000000n,
  },
  {
    address: "SP1WHYWV80ARXGFDJD63R0V87S2547H1ETZNC4B16",
    cycle82Stacked: 59444000000n,
    cycle83Stacked: 59444000000n,
  },
  {
    address: "SP20N3J7JV41062GPJ2MGWFGNQ1QSRT8Y2EEWZP14",
    cycle82Stacked: 2590000000n,
    cycle83Stacked: 2590000000n,
  },
  {
    address: "SP20NZZ0ZBAWN69Y82ABT140DS8DBG43H4YR7B5F",
    cycle82Stacked: 63603000000n,
    cycle83Stacked: 63603000000n,
  },
  {
    address: "SP2179QV23KM5J4C3CQXJPYMQ0JCY9YXGSE9QHH5D",
    cycle82Stacked: 480000000000n,
    cycle83Stacked: 480000000000n,
  },
  {
    address: "SP218F71JZ4R2ERQDKEBGA1FKVAQNZBM3HK7W8EA7",
    cycle82Stacked: 27504000000n,
    cycle83Stacked: 27504000000n,
  },
  {
    address: "SP231JVP5X4A18T60YKAXF0TP3FEZ0ZJQ1FWSQ11E",
    cycle82Stacked: 1008977000000n,
    cycle83Stacked: 1008977000000n,
  },
  {
    address: "SP23402K8H5S3YFE2MDD0QS063A1DCH15DKJYNY7T",
    cycle82Stacked: 20616000000n,
    cycle83Stacked: 20616000000n,
  },
  {
    address: "SP26A8HH1ZJWVJ044RW6S37AR573GNHJFDRRXWKD3",
    cycle82Stacked: 61526000000n,
    cycle83Stacked: 61526000000n,
  },
  {
    address: "SP281DHYZ11K3B0BQHPWBBH5SRB457270073RVVES",
    cycle82Stacked: 0n,
    cycle83Stacked: 673000000000n,
  },
  {
    address: "SP286BG9TRMCGN5C5JF4A39H3PWQZ8AYZJTESZ1YP",
    cycle82Stacked: 94401000000n,
    cycle83Stacked: 94401000000n,
  },
  {
    address: "SP28KRZCB3JDGD7ZM5Z9MVWYJN27X03Y6RRH54TP6",
    cycle82Stacked: 2565000000000n,
    cycle83Stacked: 2565000000000n,
  },
  {
    address: "SP29HNRYW6EW0QYFET68PFM6F28G2T6BKXHK798D4",
    cycle82Stacked: 580850000000n,
    cycle83Stacked: 580850000000n,
  },
  {
    address: "SP29RKAMSY8HNDC1VNBPWJVAN9C4CKG5J3GA8XJB",
    cycle82Stacked: 2298257000000n,
    cycle83Stacked: 2298257000000n,
  },
  {
    address: "SP2BXXX2YN2BTZZM93SNTYZHFPARMDHXN13QHES6M",
    cycle82Stacked: 29796000000n,
    cycle83Stacked: 29796000000n,
  },
  {
    address: "SP2DZW1E6R5NEYXRHXW1RS1M4Y55Y4M52T9633M45",
    cycle82Stacked: 112417000000n,
    cycle83Stacked: 112417000000n,
  },
  {
    address: "SP2E7W7F568R99DKATHCB5B5ZTG690RF0KAPR9BWX",
    cycle82Stacked: 235041000000n,
    cycle83Stacked: 235041000000n,
  },
  {
    address: "SP2EE2R53ZJ4XVAQ0K9XNRFDDNWQE5R48AR1R3Z2R",
    cycle82Stacked: 16708000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP2G52KJHH94FDMWW75B9EEB3TRCPXD4NKMBT3NXG",
    cycle82Stacked: 665251000000n,
    cycle83Stacked: 665251000000n,
  },
  {
    address: "SP2HP0DA4G75QM1K9S5W06GAD15MABJ6M11YQS7SV",
    cycle82Stacked: 0n,
    cycle83Stacked: 2070027000000n,
  },
  {
    address: "SP2JDKWQ77WN7S0PRCS872HFJ21ZT78P6G1WCW2B",
    cycle82Stacked: 30167000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP2QE3SKKZAY68Z3KN4TTJN41BVE3B5QVJMNKJAZB",
    cycle82Stacked: 0n,
    cycle83Stacked: 246200000000n,
  },
  {
    address: "SP2R7HA42FBVPE9QYP77XYY90C0NR6Y09KTPACQ3Y",
    cycle82Stacked: 0n,
    cycle83Stacked: 1800000000000n,
  },
  {
    address: "SP2RWVYPRJAJY35179GS0JNXXX2K9K380J7F563N0",
    cycle82Stacked: 0n,
    cycle83Stacked: 30000000000000n,
  },
  {
    address: "SP2SSHDSGHHEQN1A7Z0RP0YJ6QECE8TGQTYN594PM",
    cycle82Stacked: 328442000000n,
    cycle83Stacked: 328442000000n,
  },
  {
    address: "SP2TX10NFHAFSWJ67CSJCSZZHR0NQ8PTSHQBNG3JC",
    cycle82Stacked: 5385000000000n,
    cycle83Stacked: 5385000000000n,
  },
  {
    address: "SP2W759AWBSYJ7HCA8K5CRV06DN1WGPH7C926YHJ3",
    cycle82Stacked: 1111052000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP2YEWM6EJW0BXNDJ1C6FXXWEA6VBA1QWAYCFEBTZ",
    cycle82Stacked: 475000000000n,
    cycle83Stacked: 475000000000n,
  },
  {
    address: "SP2YGEPBKGPFR3X6HMY1FV60XJ6ACEWRNAS1GC01G",
    cycle82Stacked: 357210000000n,
    cycle83Stacked: 357210000000n,
  },
  {
    address: "SP33VQ5RY02W5496T79VM5NBHMR4CKNYX84PNRHMZ",
    cycle82Stacked: 150000000000n,
    cycle83Stacked: 150000000000n,
  },
  {
    address: "SP34T0DS0ECN32J0JK891YP6JQ8VZDHJ98MPR74GX",
    cycle82Stacked: 4919000000n,
    cycle83Stacked: 4919000000n,
  },
  {
    address: "SP35WWW7CNKJG7W1QEMRFGJY09X563GANENG9JJQK",
    cycle82Stacked: 606865000000n,
    cycle83Stacked: 606865000000n,
  },
  {
    address: "SP3888WNJZZE2P2HAJQVJANHKYTZZM765T2D0ED4V",
    cycle82Stacked: 167000000000n,
    cycle83Stacked: 167000000000n,
  },
  {
    address: "SP38B7GRE0MZ8P2W9553VF2H8CQPBWQ49TBVQYDA3",
    cycle82Stacked: 57317000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP3BSWJTYBDJGDGZ54T4T0NMBGQ6BBFZCWD44VMH9",
    cycle82Stacked: 0n,
    cycle83Stacked: 10083040000000n,
  },
  {
    address: "SP3HHP7MRDVJHDHRSZWKWB2WGZ4YHD51S7BG5YSA6",
    cycle82Stacked: 91570000000n,
    cycle83Stacked: 91570000000n,
  },
  {
    address: "SP3JV1207J29CZR1YW8TCM9GVB1WR0BSQBTPXC963",
    cycle82Stacked: 3228994000000n,
    cycle83Stacked: 3228994000000n,
  },
  {
    address: "SP3JXKKD4MAN04MC0AYJ7WKAKXYJ8RC1S60D6CVPX",
    cycle82Stacked: 0n,
    cycle83Stacked: 3731000000000n,
  },
  {
    address: "SP3K2ZCQH0Z7FXTGD0HKM1E31HW16K7VBFB87WT47",
    cycle82Stacked: 535216000000n,
    cycle83Stacked: 535216000000n,
  },
  {
    address: "SP3K8WZTPP7DM8D4N8C33XB3S110S5W9WMCPJV6VW",
    cycle82Stacked: 1331133000000n,
    cycle83Stacked: 1331133000000n,
  },
  {
    address: "SP3KC5Q27SMPSEN9M8RHM7VXN8GMHM0AVZ19TGMD6",
    cycle82Stacked: 0n,
    cycle83Stacked: 100000000000n,
  },
  {
    address: "SP3M6D6M2BS7FNEFV111ZF6WQYATNJZ89Q7MXSPAE",
    cycle82Stacked: 532054000000n,
    cycle83Stacked: 532054000000n,
  },
  {
    address: "SP3M6FBPS8WM4JA0FCHPG8J72KGW2DGDB9YTKG0A2",
    cycle82Stacked: 228726000000n,
    cycle83Stacked: 228726000000n,
  },
  {
    address: "SP3N66VSF1HAH9BP36XEAT2JZWZ45TDJXWENGS7Y5",
    cycle82Stacked: 1023428000000n,
    cycle83Stacked: 1023428000000n,
  },
  {
    address: "SP3PFGSFRCWTEWKQ6M8XCPSFX22PB20NNN9MS42V4",
    cycle82Stacked: 338529000000n,
    cycle83Stacked: 338529000000n,
  },
  {
    address: "SP3PMZXDTF0GECRZGZZQ12Z4DK2F2XZK38TXHXAQG",
    cycle82Stacked: 1848162000000n,
    cycle83Stacked: 1848162000000n,
  },
  {
    address: "SP3PX186AERH9CD2A2R73KJYGX79EXHJP23RFGCZ4",
    cycle82Stacked: 0n,
    cycle83Stacked: 1410292000000n,
  },
  {
    address: "SP3R4V17EJNWFJ5TZ3DK4JCPR5GG55WC02CFC6M75",
    cycle82Stacked: 95839000000n,
    cycle83Stacked: 95839000000n,
  },
  {
    address: "SP3S9C308H0GJQMT3PEEXHCN7210RJ1A4S5PZFT58",
    cycle82Stacked: 118054000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP3SFN52APS1B02KNW2J1TTKGESTRX8RNATYDXBCM",
    cycle82Stacked: 1334980000000n,
    cycle83Stacked: 1334980000000n,
  },
  {
    address: "SP3TQWW8KGD58T0N2VX72RAFBMS0BGA61PS52ANFF",
    cycle82Stacked: 106750000000n,
    cycle83Stacked: 106750000000n,
  },
  {
    address: "SP3W83KG17KJZZXPDZQDTRQKQRGHNFZN410R9P02E",
    cycle82Stacked: 300000000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP3WBYAEWN0JER1VPBW8TRT1329BGP9RGC5S2519W",
    cycle82Stacked: 283021000000n,
    cycle83Stacked: 0n,
  },
  {
    address: "SP3WEC9Q4NZA654SMVPX8EPJNF1D890ZS2B21H6FM",
    cycle82Stacked: 207606000000n,
    cycle83Stacked: 207606000000n,
  },
  {
    address: "SP3WGV0EADMP2RF14DV43F9AM88PEPPC9FXKHDXS5",
    cycle82Stacked: 24999000000n,
    cycle83Stacked: 24999000000n,
  },
  {
    address: "SP3WYZ13JQ4NQHGTC5XQ6K40R65PAGCH896M3T7RQ",
    cycle82Stacked: 2620000000000n,
    cycle83Stacked: 2620000000000n,
  },
  {
    address: "SP3YJ9487PS0JDDYBBVH0RW3JPY48V0A86PQGDA6V",
    cycle82Stacked: 0n,
    cycle83Stacked: 2026459000000n,
  },
  {
    address: "SP3YTHQCEX8A77NM7NZTK5VNDQPKBJCKDZNR34096",
    cycle82Stacked: 177093000000n,
    cycle83Stacked: 177093000000n,
  },
  {
    address: "SP3ZCKGQW8GSE0TSFJNC8V7W0HEQSNV67P0YST3ZS",
    cycle82Stacked: 0n,
    cycle83Stacked: 830000000n,
  },
  {
    address: "SP3ZNS0EG8FS11EAZBQ2W77PFCA1G1BQNB8PDDPY5",
    cycle82Stacked: 176746000000n,
    cycle83Stacked: 176746000000n,
  },
  {
    address: "SP5Z477DWBXEBNR1KTN8J15GEMZ433D79RJCA806",
    cycle82Stacked: 5479000000n,
    cycle83Stacked: 5479000000n,
  },
  {
    address: "SP6WZ56TPD7D90188P0EM8YXT5D0EAW3MV3N4J6N",
    cycle82Stacked: 413561000000n,
    cycle83Stacked: 413561000000n,
  },
  {
    address: "SP8QXHTJAZBXKQV7ZYK5YBQ6D29DQ50HMAV97C2S",
    cycle82Stacked: 0n,
    cycle83Stacked: 2000000000n,
  },
  {
    address: "SPBA7BPCQTPVJATE06PPRJZ5ND1QK5V6ZAAQN9B7",
    cycle82Stacked: 313304000000n,
    cycle83Stacked: 313304000000n,
  },
  {
    address: "SPC8DYBHD10DGX1AQWM5PCHW6NYMTAZWHHN5YE25",
    cycle82Stacked: 0n,
    cycle83Stacked: 5421774000000n,
  },
  {
    address: "SPCXYQ2AF41TJZ69J3MV8ZEVRNBWHTD93PH2YGEC",
    cycle82Stacked: 1432526000000n,
    cycle83Stacked: 1432526000000n,
  },
  {
    address: "SPDESG36WC08RBEMYJEXRQD8D7ESW16TPXDRZZBX",
    cycle82Stacked: 0n,
    cycle83Stacked: 766000000n,
  },
  {
    address: "SPEGKP7BK0JF4830AQY18FHH0JXVABCGV7DWFG33",
    cycle82Stacked: 1034936000000n,
    cycle83Stacked: 1034936000000n,
  },
  {
    address: "SPF1TS8E9FVS438KD9KXV3VCR228R3DZ97ZT2592",
    cycle82Stacked: 4565000000000n,
    cycle83Stacked: 4565000000000n,
  },
  {
    address: "SPFBKCWWQ5B0HKJRJ87SY0QXJZ487BE5DDMR8C8E",
    cycle82Stacked: 1580000000000n,
    cycle83Stacked: 1580000000000n,
  },
  {
    address: "SPKDKR58FY2MAWRRJ5R56BKJM9R1868276K73KWJ",
    cycle82Stacked: 576947000000n,
    cycle83Stacked: 576947000000n,
  },
  {
    address: "SPKSV1X7MA5XGJ8Y42Y3E0N9E21DHWHZ589B3ZX",
    cycle82Stacked: 191233000000n,
    cycle83Stacked: 191233000000n,
  },
  {
    address: "SPN3MVJV4MDY9GWYP6TNQN4ETS5T5D82FQ4N648Y",
    cycle82Stacked: 100000000000n,
    cycle83Stacked: 100000000000n,
  },
  {
    address: "SPN5HJN2H6H2SH0VPSVFAEB41KQT0E7Q3EPWDDJ1",
    cycle82Stacked: 193069000000n,
    cycle83Stacked: 193069000000n,
  },
  {
    address: "SPP7KGFMRTF86E4P8348BDJD6ETES2VP88C38R51",
    cycle82Stacked: 207032000000n,
    cycle83Stacked: 207032000000n,
  },
  {
    address: "SPP90JN2DSY4PHMKG613G3163A5VEQSN2KB2FAHP",
    cycle82Stacked: 444375000000n,
    cycle83Stacked: 444375000000n,
  },
  {
    address: "SPPWFFE5BC3GVC67VS3Z15M9AJRXSA8NHKP92XQ2",
    cycle82Stacked: 241177000000n,
    cycle83Stacked: 241177000000n,
  },
  {
    address: "SPQAT5WJ9Q290JT3V5MHCP2GAJP7GNC3MNB2B95A",
    cycle82Stacked: 2583000000n,
    cycle83Stacked: 2583000000n,
  },
  {
    address: "SPQZB84K0ZW6BNAVWETXHY6THQT1RYEMF930QZS2",
    cycle82Stacked: 0n,
    cycle83Stacked: 6190845000000n,
  },
  {
    address: "SPRADAE89F2YM9J9QZANK903SS63BY9XDK0HHHNV",
    cycle82Stacked: 0n,
    cycle83Stacked: 329593000000n,
  },
  {
    address: "SPRBP4PRWH2M4ZH95W1R117JCD7PS072ZQ1MC2KK",
    cycle82Stacked: 0n,
    cycle83Stacked: 687578000000n,
  },
  {
    address: "SPS49P4V2R4T28PBTW2YDDPCR5NRT36NNERZAQDX",
    cycle82Stacked: 745000000000n,
    cycle83Stacked: 745000000000n,
  },
  {
    address: "SPTW0D20AEHC07D0NZEHZBCPZ3JGST5271KSK9SA",
    cycle82Stacked: 461909000000n,
    cycle83Stacked: 461909000000n,
  },
  {
    address: "SPTWKBR2MBGZ4QW88HZ49F2XSSDSTMTD8M0FV6WE",
    cycle82Stacked: 279875000000n,
    cycle83Stacked: 279875000000n,
  },
  {
    address: "SPV6T5ANHZ4JKA58C9WY53CPJDVGW1VVQRAKPA36",
    cycle82Stacked: 483817000000n,
    cycle83Stacked: 483817000000n,
  },
  {
    address: "SPV8WPC2SE7ENBDXAJGPAK5VG32Z1PE23QY806RN",
    cycle82Stacked: 34834000000n,
    cycle83Stacked: 34834000000n,
  },
  {
    address: "SPW129P4FRMJ7TCGZ6XMN5MTAH428DWR0XJ990N1",
    cycle82Stacked: 600000000000n,
    cycle83Stacked: 600000000000n,
  },
  {
    address: "SPZCES20JGFFJ1FT1Z50TH9T6X9C95QCJD79HVSF",
    cycle82Stacked: 2750000000000n,
    cycle83Stacked: 2750000000000n,
  },
];
